name = "Create: Genesis"
author = "NEXOR_ls"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9da4ee8a38fe7195ea9a4846256aa6055c25c57111370caf43e7017ef570043"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
