name = "Create: Genesis"
author = "NEXOR_ls"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a52448ac6e1af9b65b8ddeb8af8f44cdc73ddef196a0252b7a787339c6a525e0"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
