name = "Create: Genesis"
author = "NEXOR_ls"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13eef8683d5e81517188b0bf25da49078f2b9b2d2ebc97acc2ab42c1f4c9ffe7"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
